version: '3'
services:
  redis:
    image: redis
    volumes:
      - "/root/tyk/redis/data:/data"
  mongo:
    image: mongo
    volumes:
      - "/root/tyk/mongo/db:/data/db"
  tyk_gateway:
    image: tykio/tyk-gateway
    ports:
      - "8080:8080"
    volumes:
      - "/root/tyk/gateway/apps:/opt/tyk-gateway/apps"
      - "/root/tyk/gateway/middleware:/opt/tyk-gateway/middleware"
      - "/root/tyk/gateway/js:/opt/tyk-gateway/js"
      - "/root/tyk/gateway/templates:/opt/tyk-gateway/templates"
      - "/root/tyk/gateway/tyk.conf:/opt/tyk-gateway/tyk.conf"
  tyk_dashboard:
    image: tykio/tyk-dashboard
    ports:
      - "3000:3000"
    volumes:
      - "/root/tyk/dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf"
  tyk_pump:
    image: tykio/tyk-pump-docker-pub
